/**
 * Cordon — Aave V3 Sepolia contract addresses + ABIs.
 * Source: aave-dao/aave-address-book, AaveV3Sepolia.sol (autogenerated registry).
 * All addresses are the official Aave V3 testnet deployment on Ethereum Sepolia.
 */

export const CHAIN = {
  id: 11155111,
  name: 'Ethereum Sepolia',
} as const

export const AAVE_V3_SEPOLIA = {
  /** IPool — main entry point for supply/repay/getUserAccountData */
  pool: '0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951',
  poolAddressesProvider: '0x012bAC54348C0E635dCAc9D5FB99f06F24136C9A',
  poolDataProvider: '0x3e9708d80f7B3e43118013075F7e95CE3AB31F31',
  /** Faucet — mints testnet assets for a given address */
  faucet: '0xC959483DBa39aa9E78757139af0e9a2EDEb3f42D',
} as const

/** Reserve assets available on the Aave V3 Sepolia market */
export const RESERVES = {
  USDC: {
    underlying: '0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8',
    decimals: 6,
    aToken: '0x16dA4541aD1807f4443d92D26044C1147406EB80',
  },
  DAI: {
    underlying: '0xFF34B3d4Aee8ddCd6F9AFFFB6Fe49bD371b8a357',
    decimals: 18,
    aToken: '0x29598b72eb5CeBd806C5dCD549490FdA35B13cD8',
  },
  LINK: {
    underlying: '0xf8Fb3713D459D7C1018BD0A49D19b4C44290EBE5',
    decimals: 18,
    aToken: '0x3FfAf50D4F4E96eB78f2407c090b72e86eCaed24',
  },
  WBTC: {
    underlying: '0x29f2D40B0605204364af54EC677bD022dA425d03',
    decimals: 8,
    aToken: '0x1804Bf30507dc2EB3bDEbbbdd859991EAeF6EefF',
  },
} as const

export type ReserveSymbol = keyof typeof RESERVES

/** Pool ABI fragments Cordon uses (function names as they appear in the contract ABI). */
export const POOL_ABI = {
  /** getUserAccountData(address) → (totalCollateralBase, totalDebtBase, availableBorrowsBase, currentLiquidationThreshold, ltv, healthFactor) */
  getUserAccountData:
    'function getUserAccountData(address user) view returns (uint256 totalCollateralBase, uint256 totalDebtBase, uint256 availableBorrowsBase, uint256 currentLiquidationThreshold, uint256 ltv, uint256 healthFactor)',
  /** supply(address asset, uint256 amount, address onBehalfOf, uint16 referralCode) */
  supply:
    'function supply(address asset, uint256 amount, address onBehalfOf, uint16 referralCode)',
  /** repay(address asset, uint256 amount, uint256 interestRateMode, address onBehalfOf) returns (uint256) */
  repay:
    'function repay(address asset, uint256 amount, uint256 interestRateMode, address onBehalfOf) returns (uint256)',
} as const

/** ERC-20 approve — required before the Pool can pull the top-up asset. */
export const ERC20_ABI = {
  approve: 'function approve(address spender, uint256 amount) returns (bool)',
  balanceOf: 'function balanceOf(address owner) view returns (uint256)',
} as const

/** ERC-20 decimals lookup per reserve. */
export function decimalsOf(symbol: ReserveSymbol): number {
  return RESERVES[symbol].decimals
}

/** Convert a human amount to wei for the reserve. */
export function toWei(symbol: ReserveSymbol, amount: number): string {
  const d = decimalsOf(symbol)
  return BigInt(Math.round(amount * 10 ** d)).toString()
}